### ISSUE TITLE
[Bug]: Long time to process and incorrect computed mesh of an IFC Element IfcFlowTerminal type

### ISSUE THREAD

**Issue by jespa007** [ThatOpen/engine_web-ifc#898]
### What happened?

I've attached the [Element3D 1.zip](https://github.com/user-attachments/files/16066184/Element3D.1.zip) file which it contents a single element as type FLOWTERMINAL. I found 2 issues:

1. The first issue is about of compute the mesh. In the last github code of web-ifc it takes **7 minutes and 27** seconds to process the mesh. I have checked that the last version that computes the mesh quite fast was the version 0.0.51 and it takes **2 seconds**. So the changes from versions 0.0.52 and upper this issue happen.

2. As a second issue, the result of the mesh is not correct. Again, the last version that computes the mesh well was the 0.0.51.

**RENDER RESULT MESH FLOWTERMINAL  FROM WEB-IFC 0.0.51**

![image](https://github.com/ThatOpen/engine_web-ifc/assets/7852409/f5cf78a4-98b7-4367-a803-e0683a6412cd)

**RENDER RESULT MESH FLOWTERMINAL  FROM WEB-IFC LAST CODE**

![image](https://github.com/ThatOpen/engine_web-ifc/assets/7852409/ef653c74-bbae-499e-ae28-1bc01835c489)

`Note : The issue has been tested from code downloaded at date 2024-06-28 (4 days ago).`

### Version

Latest

### What browsers are you seeing the problem on?

Chrome

**Comment by hellghostx** [comment]
Since 0.0.55 some models take "ages" to be processed by web-ifc. Usually it is connected to error output. 

For example this file (3MB)
[Vandamme_Voorbewerkingsgebouw_22047H_fase_2.zip](https://github.com/user-attachments/files/16138851/Vandamme_Voorbewerkingsgebouw_22047H_fase_2.zip)
get browser almost stuck but it is still going for 13 minutes. The result is this:

![obrazek](https://github.com/ThatOpen/engine_web-ifc/assets/26725817/c8fe79b3-a27a-46a3-abbd-141a5ea14ed8)

Aborted() error should be fixed according to #818 in next release, but that loading time is a new in 0.0.55.

But on the other hand file with 12 MB and output like this

![obrazek](https://github.com/ThatOpen/engine_web-ifc/assets/26725817/977b2140-5ef5-4081-9be7-41b854510a08)

is processing for 30s (still much longer than before)

Tested on google chrome

**Comment by jespa007** [comment]
I have tested all web-ifc from 0.47 up to 0.55 and I see this issue happens from version 0.0.52. Maybe it has to do with how bad ior good is modeled the 3D object.

**Comment by QuimMoya** [comment]
I solved an issue with IFCELLIPSES and CIRCLES in this model.

Anyway it istill takes a lot of time to process all holes, probably because they are boolean ops. We are wroking on it

![image](https://github.com/user-attachments/assets/52d40038-e222-4f3e-8c06-82554a36b10b)
My model is a simplified version of yours

**Comment by jespa007** [comment]
Thanks @QuimMoya !!! Glad to know you are mitigating these things!

**Comment by QuimMoya** [comment]
This issue is now solved
